// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crédito Fácil - Soluções Financeiras Personalizadas",
  description: "Consórcio imobiliário, financiamentos, empréstimos, saque FGTS e limpa nome. Realize seus sonhos com as melhores condições do mercado.",
  keywords: "crédito, financiamento, consórcio, empréstimo, saque FGTS, limpa nome, soluções financeiras",
  authors: [{ name: "Crédito Fácil" }],
  openGraph: {
    title: "Crédito Fácil - Soluções Financeiras Personalizadas",
    description: "Consórcio imobiliário, financiamentos, empréstimos, saque FGTS e limpa nome. Realize seus sonhos com as melhores condições do mercado.",
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "Crédito Fácil - Soluções Financeiras Personalizadas",
    description: "Consórcio imobiliário, financiamentos, empréstimos, saque FGTS e limpa nome. Realize seus sonhos com as melhores condições do mercado.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}